[package]
name = "fundx7"
version = "0.0.4"
edition = "2024"
authors = ["Tyler Neely, Yavin Arba"]
description = "Rust port of Mutable Instruments Plaits fundx7/FM synthesis engine- now ready for usage as a Node in FunDSP!"
readme = "README.md"
license = "MIT"
repository = "https://github.com/GalOzRlz/fundx7"
keywords = ["audio", "synthesis", "fm", "fundx7", "dsp"]
categories = ["multimedia::audio"]

[features]
fast_op_level_modulation = []

[dev-dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
hound = "3.5.1"
log = "0.4.28"
rustfft = "6.4.1"
[dependencies]
fundsp = "0.23.0"
